### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by pvulakh** [woojinc/Edna#2]
Great work on this! Some changes to make:

### misc
- [ ] When you view a project in List form, there are many sections, each of which has tasks whose order you can change around and you can drag a task from section to section. You can also drag and drop the order of the sections within the project itself. When you view a project in Column form, the same functionality exists but the sections are now called columns. We need to reflect this at the db level by making another table (either called `sections` or `columns`) that will have a `name`, a `next_id`, and a `prev_id` to keep track of the spot it holds within the project. Both `next_id` and `prev_id` can be null. A `section`/`column` will have many tasks, so a task will belong to the `section`/`column`. Please let me know if you have any questions on this!
- [ ] Add a joins table to represent team memberships (a user can be on many teams, and a team has many members)

### `users`
- [ ] Remove `username` column and instead add either `full_name` or `first_name`, `last_name` since Asana asks for the full name when signing up
- [ ] When a user navigates to My Profile Settings, there are additional fields that are missing from your db (`role`, `about_me`, `pronouns`). Let's add those in

### `tasks` - great work on this, very thorough!
- [ ] Add another column that references `users` to keep track of who is supposed to complete this task (can be a user other than the author!)
- [ ] Replace the `project_id` foreign key with `section_id` or `column_id` depending on which default you go with (see the note in misc section above)
- [ ] Add columns of `next_id` and `prev_id` to keep track of the order of tasks within the section/column they belong to. Both of these can be null
- [ ] Add in a `due_date` column

Let me know if you have any questions!
